version: '2.1'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfiles/mariadb/Dockerfile
    image: 9wimu9/vehicle-api-mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    ports:
      - '3303:3306'

  laravel:
    build:
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
    image: 9wimu9/vehicle-api-laravel:latest
    ports:
      - '8000:8000'
#    volumes:
#      - './:/app'
    depends_on:
      - mariadb

#vehic-LoadB-DD7UYMPF8NH7-a3b45740b59b4abf.elb.us-east-1.amazonaws.com:8000
#        #https://github.com/aws/aws-cli/issues/6242#issuecomment-1079214960
#      aws ecs update-service --cluster vehicle-api --service vehicle-api-LaravelService-ULddRaJzMxFh --region us-east-1 --enable-execute-command --force-new-deployment
#    aws ecs execute-command  \
#    --region us-east-1 \
#    --cluster vehicle-api \
#    --task 2c8f33157e3a418fb97af52ef51216c7 \
#    --container  laravel \
#    --command "/bin/bash" \
#    --interactive



