version: '2.1'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfiles/mariadb/Dockerfile
#    image: 9wimu9/auth-app-mariadb-bitnami-cloudformation
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    ports:
      - '3309:3306'

  myapp:
    build:
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
#    image: 9wimu9/auth-app-bitnami-formation-cloudformation
    ports:
      - '8002:8000'
    volumes:
      - './:/app'
    depends_on:
      - mariadb

#http://auth-loadb-5rvmh5xbgme4-58c4387b8bb2d7a6.elb.us-east-1.amazonaws.com:8000
#        #https://github.com/aws/aws-cli/issues/6242#issuecomment-1079214960
#      aws ecs update-service --cluster auth-api --service auth-api-MyappService-HLgLJ0GHOtRu --region us-east-1 --enable-execute-command --force-new-deployment
#    aws ecs execute-command  \
#    --region us-east-1 \
#    --cluster auth-api \
#    --task f574670275414f0aa173b493cfb4ad51 \
#    --container  myapp \
#    --command "/bin/bash" \
#    --interactive



